### ISSUE TITLE
not work for iOS

### ISSUE THREAD

**Issue by jinfagang** [btastic/flutter_native_image#32]
```
Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method compressImage on channel flutter_native_image)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
<asynchronous suspension>
#1      FlutterNativeImage.compressImage (package:flutter_native_image/flutter_native_image.dart:16:31)
<asynchronous suspension>
#2      _UserChatSettingsState._compressImage (package:tunnel/tab_page/tab1_children/chatchildren/user_chat_setting.dart:47:50)
<asynchronous suspension>
#3      _UserChatSettingsState._getImage (package:tunnel/tab_page/tab1_children/chatchildren/user_chat_setting.dart:54:20)
<asynchronous suspension>
#4      _UserChatSettingsState.build.<anonymous closure> (package:tunnel/tab_page/tab1_children/chatchildren/user_chat_setting.dart:99:17)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)

#6      _InkResponseState.build.<anonymous closure> (package:flutter/s<…>
```

**Comment by btastic** [comment]
Interesting..strange that you are the seemingly only one. I don't have access to an apple device right now. Maybe someone else can check? @a-leblond @acidjazz hope you don't mind paging you

**Comment by a-leblond** [comment]
I haven't tested the plugin on iOS for a while, did you try to delete the build folder and recompile the app ?

I had a similar error 2 weeks ago with a different plugin in debug mode but not in release mode, and I couldn't find out why it happened but a few days ago it started to work in debug mode..

**Comment by jinfagang** [comment]
@btastic @a-leblond Thanks for your reply, I just add this library for the very first time and it got this error, how about test on a Simulator?

**Comment by btastic** [comment]
Sorry, holidays :smile: .. you can create a simulator following these instructions: https://flutter.io/docs/get-started/install/macos#set-up-the-ios-simulator

**Comment by btastic** [comment]
Is this still an ongoing issue?

**Comment by btastic** [comment]
Closing due to inactivity. Feel free to open a new issue if this still occurs.

**Comment by aiman97adzhar** [comment]
Help! i get error in  @btastic 

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method compressImage on channel flutter_native_image)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      FlutterNativeImage.compressImage (package:flutter_native_image/flutter_native_image.dart:22:16)
