### ISSUE TITLE
Crop error in the landscape mode

### ISSUE THREAD

**Issue by Angero** [btastic/flutter_native_image#39]
I want to take photo, compress this photo and crop middle square from this image. When I use the portrait mode, I don't have any mistakes. But, if I use the landscape mode I get that mistake:

```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
PlatformException(bounds_error, Bounds are outside of the dimensions of the source image, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
<asynchronous suspension>
#2      FlutterNativeImage.cropImage (package:flutter_native_image/flutter_native_image.dart:52:31)
<asynchronous suspension>
#3      takePhoto (package:flu_kids_client/client/client_kid.dart:214:47)
<asynchronous suspension>
#4      _contactChild.<anonymous closure> (package:flu_kids_client/client/client_kid.dart:82:19)
<asynchronous suspension>
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
#16     _invoke1 (dart:ui/hooks.dart:168:13)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

There is my code:

```dart
takePhoto() async {
  // Делаем снимок камерой
  File largeImageFile = await ImagePicker.pickImage(source: ImageSource.camera);

  // Получаем ширину и высоту оригинала
  ImageProperties properties =
      await FlutterNativeImage.getImageProperties(largeImageFile.path);

  // Смотрим ориентацию экрана. От нее зависит, по какой стороне будем резать картинку.
  int size = 100;
  int quality = 80;
  int compressedWidth;
  int compressedHeight;
  if (properties.width >= properties.height) {
    compressedWidth = (properties.width * size / properties.height).round();
    compressedHeight = size;
  } else {
    compressedWidth = size;
    compressedHeight = (properties.height * size / properties.width).round();
  }
  File compressedFile = await FlutterNativeImage.compressImage(largeImageFile.path,
      quality: quality,
      targetWidth: size,
      targetHeight: (properties.height * size / properties.width).round());

  // Вырезаем квадратную середину изображения
  int originX = 0;
  int originY = 0;
  if (properties.width >= properties.height) {
    originX = ((compressedWidth - size) / 2).round();
  } else {
    originY = ((compressedHeight - size) / 2).round();
  }
  File croppedFile = await FlutterNativeImage.cropImage(compressedFile.path, originX, originY, size, size);

  Store.pageState.setState(() {
    _smallImageFile = croppedFile;
  });
}
```

Where is a mistake?

**Comment by hopkinson** [comment]
it does not work yet...

**Comment by sostenesgomes** [comment]
@Angero what was your mistake?
