### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by fvisticot** [btastic/flutter_native_image#41]
error: Exception: error: native function 'Window_sendPlatformMessage' (4 arguments) cannot be found
flutter: =====>#0      Window.sendPlatformMessage (dart:ui/window.dart:811:9)
#1      BinaryMessages._sendPlatformMessage (package:flutter/src/services/platform_messages.dart:39:15)
#2      BinaryMessages.send (package:flutter/src/services/platform_messages.dart:87:12)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:286:49)
<asynchronous suspension>
#4      FlutterNativeImage.getImageProperties (package:flutter_native_image/flutter_native_image.dart:45:33)
<asynchronous suspension>

**Comment by btastic** [comment]
Can you please provide a `flutter doctor`?

**Comment by fvisticot** [comment]
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale fr-FR)
    • Flutter version 1.1.8 at /Users/xxx/Tools/flutter
    • Framework revision 985ccb6d14 (7 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

**Comment by btastic** [comment]
Is this still an issue? I can't see it not working..

**Comment by btastic** [comment]
Closing due to inactivity. Feel free to open a new issue if this still occurs.
