### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by AlexVincent525** [btastic/flutter_native_image#56]
Hi there! I'm facing a issue that was created before #14 , and this issue happened with particular image file.
```
E/MethodChannel#flutter_native_image( 5197): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/MethodChannel#flutter_native_image( 5197): 	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:734)
E/MethodChannel#flutter_native_image( 5197): 	at com.example.flutternativeimage.FlutterNativeImagePlugin.onMethodCall(FlutterNativeImagePlugin.java:64)
E/MethodChannel#flutter_native_image( 5197): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_native_image( 5197): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_native_image( 5197): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter_native_image( 5197): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_native_image( 5197): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_native_image( 5197): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_native_image( 5197): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter_native_image( 5197): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_native_image( 5197): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter_native_image( 5197): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter ( 5197): Crop image faild: PlatformException(error, Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference, null)
```
This happened when I was trying to compress image. 
```
final path = (await getApplicationDocumentsDirectory()).path;
File file = File("$path/_temp_avatar.jpg");
file.writeAsBytes(await cropImage(state: _editorKey.currentState));
File compressedFile = await FlutterNativeImage.compressImage(
  file.path,
  quality: 100,
  targetWidth: 640,
  targetHeight: 640,
);
```
Hope you can help me with this, I'm referencing the latest commit.

**Comment by AlexVincent525** [comment]
Seems I mixed the async method with the sync one, sorry.
